name: Rotate IAM user keys

on:
  schedule:
    - cron: "37 13 * * 6"

jobs:
  rotate:
    name: rotato potato
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0

      - name: rotate aws keys
        uses: kneemaa/github-action-rotate-aws-secrets@v1.2.0
        env:
          GITHUB_ACCESS_KEY_NAME: AWS_ACCESS_KEY_ID
          GITHUB_SECRET_KEY_NAME: AWS_SECRET_ACCESS_KEY
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          IAM_USERNAME: "gh-actions-ui"
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          OWNER_REPOSITORY: ${{ github.repository }}
