# Run unit tests with yarn
name: Unit Tests
on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
      - name: Install dependencies
        run: |
          echo "//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_NPM_TOKEN }}" >> .npmrc
          yarn install --frozen-lockfile
      - name: Run unit tests
        run: yarn test
      - name: Check code formatting
        run: yarn format --check
      - name: Lint code
        run: yarn lint

